# Generated by Django 4.1.1 on 2022-10-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phonenumber', models.CharField(max_length=12)),
                ('Id_No', models.CharField(max_length=8, null=True)),
                ('code', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.CharField(max_length=20, null=True)),
                ('msg_status', models.CharField(max_length=20, null=True)),
                ('message', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('location', models.TextField(max_length=100, null=True)),
                ('seed_variety', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_variety', models.CharField(max_length=100, null=True)),
                ('cost_per_Kg', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
