# Generated by Django 4.1.2 on 2022-10-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeds',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
