# Generated by Django 4.1.1 on 2022-10-04 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisteredCompanies',
            new_name='SeedCompanies',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='Id_No',
            new_name='id_no',
        ),
    ]
