# Generated by Django 4.1.1 on 2022-10-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriApp', '0002_rename_registeredcompanies_seedcompanies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeds',
            name='quantity',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
