# Generated by Django 4.1.1 on 2022-10-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriApp', '0003_alter_seeds_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedcompanies',
            name='company_name',
            field=models.CharField(choices=[('ADC Molo', 'ADC Molo'), ('KARLO,Tigoni', 'KARLO,Tigoni'), ('Kisima Farm', 'Kisima Farm'), ('Agrico East Africa', 'Agrico East Africa'), ('Fresh Crop Limited', 'Fresh Crop Limited'), ('Singus Enterprise ', 'Singus Enterprise '), ('Egerton University Unit', 'Egerton University Unit'), ('GTIL (Apical cuttings and minitubers only', 'Apical cuttings and minitubers only'), ('Aberdare Technology Limited', 'Aberdare Technology Limited'), ('Gene Biotech seeds LTD', 'Gene Biotech seeds LTD'), ('Sigen Hortipruse Ltd', 'Sigen Hortipruse Ltd'), ('Kevian Kenya seeds (Kirinyaga seeds)', 'Kevian Kenya seeds (Kirinyaga seeds)'), ('Savannah Fresh Hort. Farmers Cooperative Society Ltd', 'Savannah Fresh Hort. Farmers Cooperative Society Ltd'), ('Mahindra and Mahindra s.Africa Ltd', 'Mahindra and Mahindra s.Africa Ltd'), ('Baraka Agricultural College (Nakuru)', 'Baraka Agricultural College (Nakuru)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seedcompanies',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seedcompanies',
            name='seed_variety',
            field=models.CharField(choices=[('Shangi', 'Shangii'), ('Dutch robijn', 'Dutch robijn'), ('Sherekea', 'Sherekea'), ('Konjo', 'Konjo'), ('Lady Amarilla', 'Lady Amarilla'), ('Musica', 'Musica')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seeds',
            name='seed_variety',
            field=models.CharField(choices=[('Shangi', 'Shangii'), ('Dutch robijn', 'Dutch robijn'), ('Sherekea', 'Sherekea'), ('Konjo', 'Konjo'), ('Lady Amarilla', 'Lady Amarilla'), ('Musica', 'Musica')], max_length=100, null=True),
        ),
    ]
