# Generated by Django 4.1.1 on 2022-10-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriApp', '0004_alter_seedcompanies_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeds',
            name='seed_variety',
            field=models.CharField(choices=[('Shangii', 'Shangii'), ('Dutch robijn', 'Dutch robijn'), ('Sherekea', 'Sherekea'), ('Konjo', 'Konjo'), ('Lady Amarilla', 'Lady Amarilla'), ('Musica', 'Musica')], max_length=100, null=True),
        ),
    ]
